CREATE TABLE usuarios(
nome VARCHAR(100),
email VARCHAR(100),
senha VARCHAR(80),
ID INT PRIMARY KEY AUTO_INCREMENT
)ENGINE=MyISAM DEFAULT CHARSET=utf8;

SELECT * FROM usuarios;

DROP TABLE usuarios;


SELECT * FROM usuarios;
